---
title: "hw03-ian-driscoll"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, error = TRUE, fig.path = 'images/')
```
## Pipelines and Redirection using bash

### 2.1 Unique teams
```{bash 2.1}
cut -d "," -f 2 nba2017-roster.csv | tail +2 | sort -u > team-names.txt
head -n 5 team-names.txt
```
### 2.2 Unique positions
```{bash 2.2}
cut -d "," -f 3 nba2017-roster.csv | tail +2 | sort -u > position-names.txt
head -n 5 position-names.txt
```
### 2.3 Counts of experiences sorted
```{bash 2.3}
cut -d "," -f 7 nba2017-roster.csv | tail +2 | sort -n | uniq -c > experience-counts.txt
head -n 5 experience-counts.txt
```
### 2.4 Clippers players
```{bash 2.4}
grep -e "team" -e "LAC" nba2017-roster.csv > LAC.csv
cat LAC.csv
```
### 2.5 Lakers age counts
```{bash 2.5}
grep "LAL" nba2017-roster.csv | cut -d "," -f 6 | sort -n | uniq -c
```
### 2.6 Number of Cleveland players
```{bash 2.6}
cut -d "," -f 2 nba2017-roster.csv | grep "CLE" | wc -l
```
### 2.7 Warriors names, heights, and weights
```{bash 2.7}
grep -e "GSW" -e "team" nba2017-roster.csv | cut -d "," -f 1,4,5 > gsw-height-weight.csv
cat gsw-height-weight.csv
```
### 2.8 Top 10 salaries
```{bash 2.8}
grep -e "player" nba2017-roster.csv | cut -d "," -f 1,8 > top10-salaries.csv
cut -d "," -f 1,8 nba2017-roster.csv | sort -t "," -n -r -k2 >> top10-salaries.csv
cat top10-salaries.csv | head -n 11
```
## Binomial Functions
```{r}
source('code/binomial-functions.R')
library(ggplot2)
# probability of geting 3 sixes in 10 rolls
bin_probability(10, 3, (1/6))

# prob plot of number of sixes with loaded die in 10 rolls
x = bin_distribution(10, 0.25)
ggplot() + geom_point(aes(x = x$success, y = x$probability)) + ggtitle("Probability of # Sixes in 10 rolls with p = 0.25")

# probability of more than 3 heads in 5 tosses with biased coin of p = 0.35 of heads
prob = 0
for (i in 4:5) {
  prob = prob + bin_probability(5, i, 0.35)
}
prob

# distribution of # heads in 15 tosses of loaded coin with p = 0.35 of heads
y = bin_distribution(15, 0.35)
ggplot() + geom_point(aes(x = y$success, y = y$probability)) + ggtitle("Distr. of # heads in 15 tosses of loaded coin with p = 0.35 of heads")
```


